title: Flexsoft Docs
theme: jekyll-theme-cayman

# Agrega navegación lateral
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      toc: true

# Opcional: activa table of contents automático
plugins:
  - jekyll-toc
