title: Flexsoft Docs
description: Guía oficial de uso de la plataforma Flexsoft
theme: just-the-docs

# Habilitar navegación lateral
just_the_docs:
  logo: "https://your-logo-url.com/logo.png" # opcional
  search_enabled: true
  show_navigation: true
  nav_sort: true
  collections:
    docs:
      name: Documentación
      permalink: /:path/

# Base path si lo subes a GitHub Pages
baseurl: "/flexsoftdocs" # cambia esto si tu repositorio se llama distinto

# URLs amigables
permalink: pretty
